service: payment-manager

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
          Resource: 
            - arn:aws:dynamodb:${self:provider.region}:*:table/Payments
        - Effect: Allow
          Action:
            - s3:GetObject
          Resource: 
            - arn:aws:s3:::${self:custom.bucketName}
            - arn:aws:s3:::${self:custom.bucketName}/*

custom:
  bucketName: all-payments-960450825

plugins:
  - serverless-s3-remover

functions:
  SQSPaymentsHandler:
    handler: src/deliveries/index.handleSqsPayments
    environment:
      discount: 5
    events:
      - sqs:
          arn: !GetAtt PaymentsQueue.Arn
          batchSize: 10
          functionResponseType: ReportBatchItemFailures
  
  S3PaymentsHandler:
    handler: src/deliveries/index.handleS3Payments
    environment:
      discount: 10
    events:
      - s3:
          bucket: ${self:custom.bucketName}
          event: s3:ObjectCreated:*
          rules:
            - suffix: .json

resources:
  Resources: 
    PaymentsQueue:
      Type: AWS::SQS::Queue
      Properties:
        FifoQueue: true
        QueueName: payments.fifo
        DelaySeconds: 0
        MessageRetentionPeriod: 86400 # 1 Day
        ContentBasedDeduplication: false
        RedrivePolicy:
          deadLetterTargetArn: !GetAtt PaymentsQueueDeadLetterQueue.Arn
          maxReceiveCount: 5

    PaymentsQueueDeadLetterQueue:
      Type: AWS::SQS::Queue
      Properties:
        FifoQueue: true
        QueueName: payments-dlq.fifo
        DelaySeconds: 0
        MessageRetentionPeriod: 345600 # 4 Days

    PaymentsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Payments
        AttributeDefinitions:
          - AttributeName: PaymentId
            AttributeType: S
        KeySchema:
          - AttributeName: PaymentId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
